# Generated by Django 5.1.6 on 2025-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
