# Generated by Django 5.1.7 on 2025-04-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='image',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
