# Generated by Django 5.1.6 on 2025-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_tasks_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='many',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
