# Generated by Django 5.1.7 on 2025-04-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_tasks_many_tasks_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
