# Generated by Django 5.1.7 on 2025-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_statistics_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='text',
        ),
        migrations.AddField(
            model_name='statistics',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
