# Generated by Django 5.1.7 on 2025-04-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_statistics_text_statistics_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
