# Generated by Django 5.1.6 on 2025-02-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registretion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='aime',
            field=models.TextField(default='', max_length=100),
        ),
    ]
