# Generated by Django 5.1.6 on 2025-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registretion', '0003_myuser_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='myuser',
            name='activation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='height',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='weights',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
