# Generated by Django 5.1.6 on 2025-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registretion', '0004_remove_myuser_avatar_myuser_activation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='activation',
        ),
        migrations.AddField(
            model_name='myuser',
            name='code',
            field=models.CharField(default='-1', max_length=6),
        ),
    ]
