# Generated by Django 5.1.6 on 2025-03-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registretion', '0005_remove_myuser_activation_myuser_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='code',
        ),
    ]
