# Generated by Django 5.1.7 on 2025-04-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registretion', '0006_remove_myuser_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='rank',
            new_name='raiting',
        ),
        migrations.AddField(
            model_name='myuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
