# Generated by Django 5.1.7 on 2025-04-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registretion', '0007_rename_rank_myuser_raiting_myuser_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='raiting',
            new_name='rating',
        ),
    ]
