# Generated by Django 5.1.7 on 2025-04-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registretion', '0008_rename_raiting_myuser_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='weights',
            new_name='weight',
        ),
    ]
