# Generated by Django 5.1.7 on 2025-04-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('registretion', '0009_rename_weights_myuser_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='things',
            field=models.ManyToManyField(to='pages.shopmodel'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='height',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
