# Generated by Django 5.1.7 on 2025-04-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_shopmodel_image'),
        ('registretion', '0010_myuser_things_alter_myuser_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='things',
            field=models.ManyToManyField(blank=True, to='pages.shopmodel'),
        ),
    ]
