# Generated by Django 5.1.7 on 2025-04-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registretion', '0011_alter_myuser_things'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='icon',
            field=models.ImageField(default='icons/1b8908034c17b1ed4318a4d6c421369c646dabb9.png', upload_to='icons/'),
        ),
    ]
