# Generated by Django 5.1.7 on 2025-04-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_tasks_many_tasks_points'),
        ('registretion', '0012_myuser_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='pages.tasks'),
        ),
    ]
